import {useEffect,useRef,useState} from 'react';
import {ArrowRight,Upload,Plus,FileText,Check,ChevronLeft,ChevronRight,Download,Layers,AlertCircle,LoaderCircle,X,PanelRightClose,PanelRightOpen,History,CheckCircle2,Settings2} from 'lucide-react';
import {api,jsonPost,artifact,Template,Job,Variant,Finding,ProviderState} from './api';
import ProviderSettings from './ProviderSettings';

const labels:Record<string,string>={sequential:'Последовательно',comparison:'Сравнение',focus:'Акценты'};
const auditStatuses:Record<string,string>={complete:'выполнена',partial:'выполнена частично',failed:'ошибка',not_run:'не выполнена'};
const repairStatuses:Record<string,string>={not_needed:'не требовалось',unchanged:'без изменений',applied:'применено',failed:'ошибка',skipped_budget:'пропущено: лимит времени'};
const statuses:Record<string,string>={queued:'В очереди',running:'В работе',completed:'Готово',partial:'Частично',failed:'Ошибка',cancelled:'Отменено',interrupted:'Прервано'};
type Content={title:string;brief?:string;sections?:unknown[];synthetic?:boolean;purpose?:string;language?:string};

export default function App(){
 const [templates,setTemplates]=useState<Template[]>([]),[template,setTemplate]=useState<Template|null>(null);
 const [jobs,setJobs]=useState<Job[]>([]),[job,setJob]=useState<Job|null>(null),[view,setView]=useState<'new'|'result'|'settings'>('new');
 const [provider,setProvider]=useState<ProviderState|null>(null),[previousView,setPreviousView]=useState<'new'|'result'>('new');
 function providerSaved(p:ProviderState){setProvider(p);setLive(p.ready)}
 function settings(){if(view!=='settings')setPreviousView(view);setView('settings');setError('')}
 const [title,setTitle]=useState(''),[brief,setBrief]=useState(''),[content,setContent]=useState<Content|null>(null);
 const [mode,setMode]=useState('offline'),[live,setLive]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [variantName,setVariantName]=useState('sequential'),[slideNo,setSlideNo]=useState(0),[auditOpen,setAuditOpen]=useState(true),[selected,setSelected]=useState<string[]>([]),[showOverlays,setShowOverlays]=useState(true);
 const input=useRef<HTMLInputElement>(null),contentInput=useRef<HTMLInputElement>(null);
 const variant=job?.result?.variants.find(v=>v.name===variantName)||job?.result?.variants[0];
 const slide=variant?.slides[slideNo];const running=job && ['queued','running'].includes(job.status);
 useEffect(()=>{api<Template[]>('/templates').then(setTemplates).catch(e=>setError(e.message));api<Job[]>('/jobs').then(setJobs).catch(()=>{});api<ProviderState>('/provider').then(providerSaved).catch(()=>{api<{live_configured:boolean}>('/health').then(h=>setLive(h.live_configured)).catch(()=>{})})},[]);
 useEffect(()=>{if(!running||!job)return;const id=job.id;const timer=setInterval(()=>{api<Job>('/jobs/'+id).then(j=>{setJob(j);setJobs(old=>[j,...old.filter(x=>x.id!==j.id)]);}).catch(e=>setError(e.message));},1500);return()=>clearInterval(timer)},[job?.id,job?.status]);
 async function upload(file:File){setBusy(true);setError('');try{const data=new FormData();data.append('file',file);const t=await api<Template>('/templates',{method:'POST',body:data});setTemplates(old=>[t,...old]);setTemplate(t)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function loadExample(){setError('');try{const c=await api<Content>('/example');setContent(c);setTitle(c.title);setBrief(c.brief||'')}catch(e){setError((e as Error).message)}}
 async function loadContent(file:File){setError('');try{const raw=await file.text();if(file.name.endsWith('.json')){const c=JSON.parse(raw) as Content;setContent(c);setTitle(c.title||'');setBrief(c.brief||'')}else{setContent(null);setBrief(raw)}}catch{setError('Не удалось прочитать материалы. Нужен JSON, Markdown или текст.')}}
 async function generate(){if(!template)return;setBusy(true);setError('');try{const j=await jsonPost<Job>('/jobs',{template_id:template.id,content:{...(content||{}),title:title.trim(),brief,language:'ru'},mode,slide_count:12,variants:Object.keys(labels)});setJob(j);setJobs(old=>[j,...old]);setView('result');setSlideNo(0);setSelected([]);setVariantName('sequential')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function repair(){if(!job||!variant)return;setBusy(true);setError('');try{const j=await jsonPost<Job>(`/jobs/${job.id}/repair`,{variant:variant.name,finding_ids:selected});setJob(j);setJobs(old=>[j,...old]);setSelected([]);setSlideNo(0)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function open(j:Job){setJob(j);setView('result');setSlideNo(0);setVariantName(j.result?.variants[0]?.name||'sequential');setSelected([])}
 const findings=variant?.findings.filter(f=>!['passed'].includes(f.status))||[];
 const critical=findings.filter(f=>f.severity==='error').length;
 return <div className="workspace">
  <aside className="sidebar">
   <a className="brand" href="/" aria-label="Форма — главная"><span className="brand-symbol"><i/><i/><i/></span>форма<span className="brand-dot">.</span></a>
   <button className="new-button" onClick={()=>{setView('new');setError('')}}><Plus size={17}/>Новая презентация</button>
   <div className="nav-label"><History size={15}/>Последние работы</div>
   <nav aria-label="Презентации">{jobs.length===0?<p className="history-empty">Здесь появятся ваши презентации</p>:jobs.map(j=><button key={j.id} className={'history-item '+(job?.id===j.id&&view==='result'?'active':'')} onClick={()=>open(j)}><FileText size={16}/><span>{j.payload.request?.content?.title||'Презентация'}<small>{statuses[j.status]||j.status}</small></span></button>)}</nav>
   <div className="sidebar-bottom"><button className={'settings-nav '+(view==='settings'?'active':'')} onClick={settings}><Settings2 size={16}/><span>Подключение модели<small>{provider?.model||'Настроить AI-генерацию'}</small></span></button><span className="local-dot"/>Локальное рабочее пространство<small>Ваш шаблон. Ваши правила.</small></div>
  </aside>
  <main className="main">
   <header className="topbar"><span>Рабочее пространство <span className="separator">/</span> {view==='settings'?'Подключение модели':view==='new'?'Новая презентация':job?.payload.request?.content?.title}</span><button className="topbar-settings" aria-label="Настройки подключения модели" onClick={settings}><Settings2 size={16}/><span>Модель</span></button></header>
   {error&&<div className="error-banner" role="alert"><AlertCircle size={18}/><span>{error}</span><button aria-label="Закрыть сообщение" onClick={()=>setError('')}><X size={16}/></button></div>}
   {view==='settings'?<ProviderSettings onClose={()=>setView(previousView)} onSaved={providerSaved}/>:view==='new'?<div className="create-page">
    <div className="intro"><h1>Содержание — ваше.<br/><span>Оформление — по шаблону.</span></h1><p>Превратите материалы в редактируемую презентацию.<br/>Сервис изучит ваш стиль и предложит три варианта вёрстки.</p></div>
    <div className="create-layout"><section className="brief-panel">
     <div className="section-heading"><span className="step">1</span><h2>Выберите шаблон</h2><span className="file-hint">PPTX · до 100 МБ</span></div>
     <input ref={input} type="file" accept=".pptx" className="visually-hidden" aria-label="Загрузить PPTX-шаблон" onChange={e=>{if(e.target.files?.[0])upload(e.target.files[0]);e.target.value=''}}/>
     <button className={'upload-zone '+(template?'loaded':'')} disabled={busy} onClick={()=>input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(e.dataTransfer.files[0])upload(e.dataTransfer.files[0])}}>
      <span className="upload-icon">{busy?<LoaderCircle className="spin"/>:template?<Check/>:<Upload/>}</span><strong>{template?template.filename:'Перетащите фирменный шаблон'}</strong><span>{template?`${template.slides} слайдов · ${template.patterns} композиций`:'или выберите файл на компьютере'}</span>
     </button>
     {templates.length>0&&<label className="saved-templates">Загруженные шаблоны<select value={template?.id||''} onChange={e=>setTemplate(templates.find(t=>t.id===e.target.value)||null)}><option value="">Выберите шаблон</option>{templates.map(t=><option key={t.id} value={t.id}>{t.filename}</option>)}</select></label>}
     <div className="section-heading content-heading"><span className="step">2</span><h2>Добавьте содержание</h2><button className="text-button" onClick={()=>contentInput.current?.click()}>Загрузить файл</button></div>
     <input ref={contentInput} className="visually-hidden" type="file" accept=".json,.md,.txt" aria-label="Загрузить материалы" onChange={e=>{if(e.target.files?.[0])loadContent(e.target.files[0]);e.target.value=''}}/>
     <label className="field">Название презентации<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Например, запуск нового продукта" maxLength={500}/></label>
     <label className="field">Бриф и исходные материалы<textarea value={brief} onChange={e=>{setBrief(e.target.value);if(content)setContent(null)}} placeholder="Для кого эта презентация? Какие тезисы и факты важно показать? Каждый абзац станет отдельным смысловым блоком." rows={6}/></label>
     {content?.sections&&<p className="content-count"><CheckCircle2 size={16}/>{content.sections.length} разделов в контент-пакете{content.synthetic?' · демонстрационные данные':''}</p>}
     <button className="text-button demo-link" onClick={loadExample}>Попробовать на демонстрационном содержании <ArrowRight size={14}/></button>
     <div className="generate-row"><label className="mode-select">Режим<select value={mode} onChange={e=>setMode(e.target.value)}><option value="offline">Без модели · проверка пайплайна</option><option value="live" disabled={!live}>AI-планирование{!live?' · настройте модель':''}</option></select></label><button className="primary" disabled={!template||!title.trim()||(!brief.trim()&&!content?.sections?.length)||busy||(mode==='live'&&!live)} onClick={generate}>Создать презентацию <ArrowRight size={17}/></button></div><div className="generation-provider"><span>{live?`AI-модель: ${provider?.model||'настроена'}`:'Для AI-генерации подключите модель.'}{mode==='live'&&!live?' Сохранённое подключение больше не готово.':''}</span><button className="text-button" onClick={settings}>{live?'Настроить':'Подключить модель'}<ArrowRight size={13}/></button></div>
    </section>
    <aside className="explain-panel"><div className="preview-demo" aria-hidden="true"><div className="paper back"/><div className="paper front"><span className="paper-line small"/><span className="paper-title">Ваш стиль.<br/>Новые идеи.</span><div className="mini-composition"><span/><span/><span/></div><div className="paper-footer"><span/><b>01</b></div></div><span className="native-label"><Layers size={14}/>Редактируемый PPTX</span></div>
     <h3>Дизайн начинается с вашего файла</h3><p>Цвета, шрифты и расположение блоков извлекаются из шаблона. Фирменный стиль сохраняется при смене содержания.</p>
     <div className="outcome"><Check size={16}/><div><strong>Три варианта</strong><span>Разные композиции, единое содержание</span></div></div><div className="outcome"><Check size={16}/><div><strong>Проверка перед экспортом</strong><span>Проблемы видны прямо на слайдах</span></div></div><div className="outcome"><Check size={16}/><div><strong>PPTX, PDF и HTML</strong><span>Для редактирования, отправки и просмотра</span></div></div>
     {template&&<div className="template-truth"><strong>Из вашего шаблона</strong><div className="swatches">{template.colors.map((c,i)=><span key={i} style={{background:'#'+c}} title={'#'+c}/>)}</div><small>{template.fonts.slice(0,4).join(' · ')}</small></div>}
    </aside></div>
   </div>:<div className="result-page">
    <div className="result-heading"><div><h1>{job?.payload.request?.content?.title}</h1><p>{job?.result?.template_name||'Подготовка презентации'}{job?.result&&` · ${job.result.seconds} с`}</p></div><span className={'status '+(job?.status||'')}>{running&&<LoaderCircle size={14} className="spin"/>}{statuses[job?.status||'']}</span></div>
    {running&&<div className="progress-strip" role="status"><LoaderCircle size={18} className="spin"/><span>{job?.stage}<small>Результаты появятся по мере готовности вариантов</small></span><button className="text-button" onClick={()=>job&&jsonPost(`/jobs/${job.id}/cancel`,{}).catch(e=>setError(e.message))}>Отменить</button></div>}
    {job?.error&&<div className="error-banner" role="alert"><AlertCircle size={18}/>{job.error}</div>}
    {job?.result?.mode==='offline'&&<div className="mode-notice">Диагностический запуск без модели. Композиции созданы из исходных разделов; смысловая проверка не выполнена.</div>}
    {job?.result?.inference&&job.result.mode==='live'&&<div className="inference-summary"><strong>AI-генерация · {job.result.inference.provider==='openrouter'?'OpenRouter':'OpenAI-совместимый сервис'}</strong><span>Проверка изображений: {auditStatuses[job.result.inference.audit.status]||job.result.inference.audit.status} · {job.result.inference.audit.coverage.length} / {job.result.inference.audit.total_slides??job.result.variants.reduce((n,v)=>n+v.slides.length,0)} слайдов</span>{job.result.inference.competition_mode===false&&<span>Режим разработки · конкурсные ограничения отключены</span>}</div>}
    {variant&&job?<>
     <div className="result-toolbar"><div className="variant-tabs" role="tablist" aria-label="Варианты вёрстки">{job.result?.variants.map(v=><button role="tab" aria-selected={v.name===variant.name} key={v.name} className={v.name===variant.name?'selected':''} onClick={()=>{setVariantName(v.name);setSlideNo(0);setSelected([])}}>{labels[v.name]}</button>)}</div><div className="exports">{variant.files.filter(f=>/\.(pptx|pdf|html|md)$/.test(f)).map(f=><a key={f} href={artifact(job.id,variant.name,f)} download><Download size={14}/>{f==='speech.md'?'Текст выступления':f.split('.').pop()?.toUpperCase()}</a>)}<button className="icon-button" title={auditOpen?'Скрыть аудит':'Показать аудит'} onClick={()=>setAuditOpen(!auditOpen)}>{auditOpen?<PanelRightClose size={18}/>:<PanelRightOpen size={18}/>}</button></div></div>
     <div className={'editor '+(!auditOpen?'wide':'')}><aside className="filmstrip" aria-label="Слайды">{variant.slides.map((s,i)=><button key={s.number} className={i===slideNo?'current':''} onClick={()=>setSlideNo(i)}><span>{String(i+1).padStart(2,'0')}</span>{variant.render.images[i]?<img src={artifact(job.id,variant.name,variant.render.images[i])} alt={s.title}/>:<div className="thumb-fallback">{s.title}</div>}</button>)}</aside>
      <section className="canvas-area" aria-label="Предпросмотр слайда"><div className="slide-canvas">{slide&&variant.render.images[slideNo]?<img src={artifact(job.id,variant.name,variant.render.images[slideNo])} alt={slide.title}/>:<div className="no-render"><FileText size={32}/><h3>Изображение слайда недоступно</h3><p>{variant.render.error||'Рендеринг не выполнен'}</p><p>Редактируемый PPTX можно скачать выше.</p></div>}
       {showOverlays&&findings.filter(f=>f.slide===slideNo+1&&f.box).map(f=><span key={f.id} className={'finding-overlay '+f.severity} title={f.message} style={{left:(f.box!.x/variant.width*100)+'%',top:(f.box!.y/variant.height*100)+'%',width:(f.box!.w/variant.width*100)+'%',height:(f.box!.h/variant.height*100)+'%'}}/>)}
      </div><div className="canvas-caption"><button className="icon-button" disabled={slideNo===0} aria-label="Предыдущий слайд" onClick={()=>setSlideNo(n=>n-1)}><ChevronLeft size={18}/></button><span>{slideNo+1} / {variant.slides.length}</span><button className="icon-button" disabled={slideNo===variant.slides.length-1} aria-label="Следующий слайд" onClick={()=>setSlideNo(n=>n+1)}><ChevronRight size={18}/></button><span className="pattern-caption">{slide?.pattern_id} · {slide?.source_ids.join(', ')}</span></div>{slide?.speaker_notes&&<details className="speaker-notes"><summary>Текст выступления к слайду</summary><p>{slide.speaker_notes}</p></details>}</section>
      {auditOpen&&<aside className="audit-panel"><div className="audit-title"><h2>Проверка слайдов</h2><span>{findings.length}</span></div><p className="audit-summary">{critical?`${critical} замечаний требуют внимания`:'Критических замечаний не найдено'}<small>Непроверенные пункты показаны отдельно</small></p><label className="overlay-switch"><input type="checkbox" checked={showOverlays} onChange={e=>setShowOverlays(e.target.checked)}/>Показать области на слайде</label><div className="findings">{findings.map(f=><FindingItem key={f.id} f={f} checked={selected.includes(f.id)} onToggle={()=>setSelected(s=>s.includes(f.id)?s.filter(id=>id!==f.id):[...s,f.id])} onSlide={()=>{if(f.slide)setSlideNo(f.slide-1)}}/>)}{findings.length===0&&<p className="empty-audit">Замечаний в выполненных проверках нет.</p>}</div><button className="primary repair-button" disabled={!selected.length||!!running||busy} onClick={repair}>Исправить выбранное{selected.length?` (${selected.length})`:''}</button><p className="repair-note">Будет создана новая версия. Исходная сохранится.</p></aside>}
     </div><details className="run-details"><summary>Ограничения и сведения о запуске</summary>{variant.warnings.map((w,i)=><p key={i}>{w}</p>)}<p>Подготовка шаблона: {job.result?.timing?.preparation_seconds ?? "—"} с · Все варианты и текст: {job.result?.timing?.generation_seconds ?? "—"} с / 300 с</p><p>Вариант: {variant.seconds} с · Рендеринг: {variant.render.status}</p>{job.result?.inference&&<><p>Модели: {[...new Set(job.result.inference.calls.map(c=>c.model).filter(Boolean))].join(' · ')||'—'} · Вызовы API: {job.result.inference.calls.length}</p><p>Автоматическое исправление: {repairStatuses[job.result.inference.repair.status]||job.result.inference.repair.status}</p>{job.result.inference.audit.error&&<p>Ошибка визуальной проверки: {job.result.inference.audit.error}</p>}{job.result.usage&&<p>Использование: {Object.entries(job.result.usage).map(([key,value])=>`${key}: ${value}`).join(' · ')}</p>}</>}</details>
    </>:!running&&<div className="empty-result"><FileText size={40}/><p>Готовых вариантов пока нет</p><button className="text-button" onClick={()=>setView('new')}>Вернуться к материалам</button></div>}
   </div>}
   <footer className="app-footer"><span>Форма · Цифровой дизайнер презентаций</span><span>Содержание и оформление — под вашим контролем</span></footer>
  </main>
 </div>
}
function FindingItem({f,checked,onToggle,onSlide}:{f:Finding;checked:boolean;onToggle:()=>void;onSlide:()=>void}){return <div className={'finding '+f.severity}><div className="finding-top"><span>{f.status==='not_run'?'Не проверено':f.kind==='heuristic'?'Оценка':f.kind==='contextual'?'Смысл':'Проверка'}</span>{f.slide&&<button onClick={onSlide}>Слайд {f.slide}</button>}</div><p>{f.message}</p>{f.repair&&<label><input type="checkbox" checked={checked} onChange={onToggle}/>Подобрать размер текста</label>}</div>}
