import {useEffect, useState} from 'react';
import {ArrowLeft, CheckCircle2, AlertCircle, LoaderCircle, Settings2} from 'lucide-react';
import {api, ProviderConfig, ProviderState, ProviderTest} from './api';

const blank:ProviderConfig={provider:'custom',base_url:'',model:'',vision_enabled:false,vision_model:'',json_mode:true,competition_mode:true,model_license:'',model_parameters_b:0,model_card:'',vision_license:'',vision_parameters_b:0,vision_card:''};
function editable(p:ProviderState):ProviderConfig{return Object.fromEntries(Object.keys(blank).map(k=>[k,p[k as keyof ProviderConfig]])) as ProviderConfig}
export default function ProviderSettings({onClose,onSaved}:{onClose:()=>void;onSaved:(p:ProviderState)=>void}){
 const [saved,setSaved]=useState<ProviderState|null>(null),[draft,setDraft]=useState<ProviderConfig>(blank);
 const [key,setKey]=useState(''),[clearKey,setClearKey]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState('');
 const [error,setError]=useState(''),[notice,setNotice]=useState(''),[models,setModels]=useState<{id:string}[]>([]),[catalogNote,setCatalogNote]=useState(''),[test,setTest]=useState<ProviderTest|null>(null);
 const dirty=!!saved&&(JSON.stringify(draft)!==JSON.stringify(editable(saved))||!!key||clearKey);
 const endpointChanged=!!saved&&draft.base_url.trim().replace(/\/+$/,'')!==saved.base_url;
 async function load(){setLoading(true);setError('');try{const p=await api<ProviderState>('/provider');setSaved(p);setDraft(editable(p));onSaved(p)}catch{setError('Не удалось загрузить настройки. Повторите загрузку.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 function change(values:Partial<ProviderConfig>){setDraft(d=>({...d,...values}));setTest(null);setNotice('Есть несохранённые изменения. Проверка станет доступна после сохранения.');setError('');if('base_url' in values||'provider' in values){setModels([]);setCatalogNote('')}}
 function receive(p:ProviderState){setSaved(p);setDraft(editable(p));setKey('');setClearKey(false);setTest(null);onSaved(p)}
 async function save(e:React.FormEvent){e.preventDefault();setBusy('save');setError('');try{const p=await api<ProviderState>('/provider',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...draft,api_key:key,clear_key:clearKey})});receive(p);setNotice('Настройки сохранены. Соединение ещё не проверено.')}catch{setError('Не удалось сохранить настройки. Проверьте адрес и доступность сервиса. Введённые данные остались в форме.')}finally{setBusy('')}}
 async function catalog(){setBusy('catalog');setCatalogNote('');try{const r=await api<{models:{id:string}[]}>('/provider/models');setModels(r.models);setCatalogNote(r.models.length?`Доступно моделей: ${r.models.length}. Выберите ID в поле ниже или введите его вручную.`:'Каталог пуст. Введите ID модели вручную.')}catch{setCatalogNote('Каталог недоступен. Введите ID модели вручную — это не мешает подключению.')}finally{setBusy('')}}
 async function probe(){setBusy('test');setError('');setTest(null);try{setTest(await api<ProviderTest>('/provider/test',{method:'POST'}));setNotice('')}catch{setError('Проверка не выполнена. Проверьте сохранённый адрес, ключ и ID модели, затем повторите попытку.')}finally{setBusy('')}}
 async function reset(){setBusy('reset');setError('');try{const p=await api<ProviderState>('/provider',{method:'DELETE'});receive(p);setModels([]);setCatalogNote('');setNotice('Подключение и сохранённый ключ удалены.')}catch{setError('Не удалось удалить подключение. Настройки остались без изменений.')}finally{setBusy('')}}
 const metadata=(vision=false)=>{const prefix=vision?'vision':'model';return <div className="provider-metadata"><label className="field">Лицензия {vision?'визуальной':'текстовой'} модели<select value={draft[`${prefix}_license`]} onChange={e=>change({[`${prefix}_license`]:e.target.value})}><option value="">Не указана</option><option value="MIT">MIT</option><option value="Apache-2.0">Apache-2.0</option><option value="other">Другая / неизвестна</option></select></label><label className="field">Параметры {vision?'визуальной':'текстовой'} модели, млрд<input type="number" min="0" max="10000" step="any" value={draft[`${prefix}_parameters_b`]||''} placeholder="Например, 7" onChange={e=>change({[`${prefix}_parameters_b`]:Number(e.target.value)})}/></label><label className="field model-card">Карточка {vision?'визуальной':'текстовой'} модели<input type="url" value={draft[`${prefix}_card`]} placeholder="https://…" onChange={e=>change({[`${prefix}_card`]:e.target.value})}/></label></div>};
 return <div className="provider-page">
  <button className="text-button back-link" onClick={()=>{setKey('');onClose()}}><ArrowLeft size={15}/>Вернуться к презентации</button>
  <div className="provider-heading"><div><h1>Подключение модели</h1><p>OpenRouter или любой сервис с OpenAI-совместимым API.<br/>Настройте один раз и выбирайте AI-режим при создании презентации.</p></div><Settings2 size={25} aria-hidden="true"/></div>
  {loading?<p className="provider-loading" role="status"><LoaderCircle size={18} className="spin"/>Загружаем настройки…</p>:!saved?<div className="provider-feedback" role="alert"><p>{error}</p><button className="secondary" onClick={load}>Повторить загрузку</button></div>:<>
  <div className={'connection-state '+(saved.ready?'ready':'')} role="status"><span className="connection-dot"/><div><strong>{saved.ready?'Настройки готовы к AI-генерации':'Подключение требует настройки'}</strong><p>{saved.ready?`${saved.model} · ${saved.competition_mode?'конкурсный режим':'режим разработки'}`:'Сохраните адрес и модель. Для конкурсного режима также заполните сведения о лицензии.'}</p>{dirty&&<small>Сейчас показан статус сохранённого подключения.</small>}</div></div>
  <form onSubmit={save} className="provider-layout">
   <div className="provider-form">
    <fieldset disabled={!!busy}><legend>Сервис и доступ</legend>
     <label className="field">Провайдер<select value={draft.provider} onChange={e=>change({provider:e.target.value as ProviderConfig['provider'],base_url:e.target.value==='openrouter'?'https://openrouter.ai/api/v1':''})}><option value="custom">OpenAI-совместимый сервис</option><option value="openrouter">OpenRouter</option></select></label>
     <label className="field">Base URL<input type="url" required value={draft.base_url} onChange={e=>change({base_url:e.target.value})} placeholder="https://api.example.com/v1" aria-describedby="endpoint-note"/></label><p className="field-note" id="endpoint-note">Адрес API с префиксом версии, без /chat/completions. Для локального сервера допустим HTTP и пустой ключ.</p>
     <label className="field">API-ключ<input type="password" value={key} autoComplete="off" spellCheck={false} maxLength={4096} onChange={e=>{setKey(e.target.value);setClearKey(false);setTest(null);setNotice('Ключ изменён. Сохраните настройки перед проверкой.')}} placeholder={saved.has_key&&!endpointChanged?'Ключ сохранён — оставьте поле пустым':'Введите ключ сервиса'} aria-describedby="key-note"/></label><p className="field-note" id="key-note">Ключ хранится на сервере этого рабочего пространства и не возвращается в браузер. Введённый ключ исчезнет из формы после сохранения или выхода.</p>
     {endpointChanged&&saved.has_key&&<p className="provider-warning">Адрес изменён. Старый ключ не переносится на новый адрес: при необходимости введите новый.</p>}
     {saved.has_key&&<label className="provider-toggle"><input type="checkbox" checked={clearKey} onChange={e=>{setClearKey(e.target.checked);setKey('');setTest(null);setNotice('Изменение ключа применится после сохранения.')}}/><span>Удалить сохранённый ключ при сохранении</span></label>}
    </fieldset>
    <fieldset disabled={!!busy}><legend>Модель для содержания</legend><p className="section-description">Планирует структуру и выбирает композиции. Текст выступления собирается из ваших фактов. Сначала сохраните адрес и ключ, чтобы запросить каталог.</p>
     <div className="model-field"><label className="field">ID текстовой модели<input list="provider-models" value={draft.model} maxLength={200} onChange={e=>change({model:e.target.value})} placeholder="Введите ID или выберите из каталога"/></label><button type="button" className="secondary" disabled={dirty||!saved.base_url} onClick={catalog}>{busy==='catalog'?<LoaderCircle size={16} className="spin"/>:null}Загрузить каталог</button></div>
     <datalist id="provider-models">{models.map(m=><option key={m.id} value={m.id}/>)}</datalist>{catalogNote&&<p className="field-note" role="status">{catalogNote}</p>}
     <label className="provider-toggle"><input type="checkbox" checked={draft.json_mode} onChange={e=>change({json_mode:e.target.checked})}/><span>Запрашивать JSON-ответ<small>Отключите, если сервис не поддерживает response_format.</small></span></label>
    </fieldset>
    <fieldset disabled={!!busy}><legend>Проверка изображений слайдов</legend><label className="provider-toggle"><input type="checkbox" checked={draft.vision_enabled} onChange={e=>change({vision_enabled:e.target.checked})}/><span>Подключить визуальную модель<small>Отправляет изображения слайдов для проверки оформления. Дополнительные запросы могут тарифицироваться.</small></span></label>
     {draft.vision_enabled?<><label className="field">ID визуальной модели<input list="provider-models" value={draft.vision_model} maxLength={200} onChange={e=>change({vision_model:e.target.value})} placeholder="ID модели с поддержкой изображений"/></label><p className="field-note">Используется тот же сервис и ключ. Проверьте поддержку изображений у выбранной модели.</p></>:<p className="field-note">Без визуальной модели проверка изображений будет отмечена как невыполненная.</p>}
    </fieldset>
    <fieldset disabled={!!busy}><legend>Условия использования моделей</legend><label className="provider-toggle"><input type="checkbox" checked={draft.competition_mode} onChange={e=>change({competition_mode:e.target.checked})}/><span>Конкурсный режим<small>Только модели до 35 млрд параметров включительно с лицензией MIT или Apache-2.0.</small></span></label>
     {!draft.competition_mode&&<p className="provider-warning">Режим разработки: ограничения по лицензии и размеру отключены. Результаты такого запуска не подтверждают соответствие конкурсным условиям.</p>}
     <p className="section-description">Укажите сведения из карточки модели. Каталог API не подтверждает лицензию и размер; эти данные остаются вашей декларацией.</p>
     {metadata()}{draft.vision_enabled&&<><h3 className="vision-metadata-heading">Сведения о визуальной модели</h3>{metadata(true)}</>}
    </fieldset>
    {error&&<p className="provider-feedback failure" role="alert"><AlertCircle size={17}/>{error}</p>}
    {notice&&<p className="provider-feedback" role="status">{notice}</p>}
    <div className="provider-actions"><button className="primary" type="submit" disabled={!!busy||!dirty}>{busy==='save'?<LoaderCircle size={16} className="spin"/>:<CheckCircle2 size={16}/>}Сохранить настройки</button><button className="text-button" type="button" disabled={!!busy} onClick={()=>{setKey('');onClose()}}>Закрыть</button></div>
   </div>
   <aside className="provider-check"><h2>Проверка соединения</h2><p>После сохранения отправьте короткий пробный запрос. Он проверит ответ текстовой модели{saved.vision_enabled?' и приём изображения визуальной моделью':''}.</p><p>Сервис может списать средства за этот запрос. Проверка запускается только по кнопке.</p>
    {saved.issues.length>0&&<ul className="provider-issues">{saved.issues.map(issue=><li key={issue}>{issue}</li>)}</ul>}
    <button type="button" className="secondary" disabled={!!busy||dirty||!saved.ready} onClick={probe}>{busy==='test'?<LoaderCircle size={16} className="spin"/>:<CheckCircle2 size={16}/>}Проверить соединение</button>
    {dirty&&<p className="field-note">Сначала сохраните изменения.</p>}
    {test&&<div className={'provider-feedback '+(test.ok?'success':'failure')} role="status"><strong>{test.ok?'Соединение проверено':'Соединение не прошло проверку'}</strong><p>{test.message}</p>{test.model&&<p>Модель: {test.model}</p>}{test.seconds!==undefined&&<p>Время ответа: {test.seconds} с</p>}{test.vision&&<p>{test.vision==='passed'?'Приём изображения проверен.':'Визуальная проверка отключена.'}</p>}</div>}
    <p className="field-note">Успешный ответ не оценивает качество готовой презентации и не подтверждает лицензию модели.</p>
    <div className="provider-reset"><h3>Отключить сервис</h3><p>Удалит адрес, настройки моделей и сохранённый ключ. Презентации останутся в истории.</p><button type="button" className="text-button danger-text" disabled={!!busy} onClick={reset}>Удалить подключение и ключ</button></div>
   </aside>
  </form></>}
 </div>
}
